name: Publish to turntable-spoonbill on PYPI

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    permissions:
      id-token: write 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install uv
        uses: astral-sh/setup-uv@v5.1.0
      - name: Build a binary wheel and a source tarball
        run: uv build
      - name: publish
        run: uv publish
